name: Firebase Deploy
on:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * *'
jobs:
  firebase_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Lint site
        run: npm run lint

      - name: Build site
        run: npm run build
        env:
          YOUTUBE: '${{ secrets.YOUTUBE }}'

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MICHAELSOLATI_COM }}
          channelId: live
          projectId: michaelsolati-com